### ISSUE TITLE
Incorrect PHY_ARD

### ISSUE THREAD

**Issue by Mobivlad** [aasandroqq/Ethernet_TCP#1]
https://github.com/aasandroqq/Ethernet_TCP/blob/095483c96466dff0f62c85f4e554145b76a8bf49/lab3/Project/Lab3/Ethernet_TCP/inc/stm32f4x7_eth_bsp.h#L53

![image](https://user-images.githubusercontent.com/17147322/78146612-0e4c5f00-743b-11ea-9fba-70f37172f266.png)

**Comment by aasandroqq** [comment]
Thank you for your issue.
